services:
    db:
        container_name: posthog_db
        environment:
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
            POSTGRES_USER: posthog
        image: postgres:13-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
    redis:
        container_name: posthog_redis
        image: redis:6-alpine
    #traefik:
     #   build:
      #      context: .
       #     dockerfile: docker/traefik/Dockerfile
       # image: production_traefik
       # depends_on:
           # - web
        #volumes:
            #- production_traefik:/etc/traefik/acme:z
        #ports:
        #- "0.0.0.0:80:80"
        #- "0.0.0.0:443:443"
    web:
        container_name: posthog_web
        depends_on:
            - db
            - redis
        environment:
            DATABASE_URL: postgres://posthog:posthog@db:5432/posthog
            REDIS_URL: redis://redis:6379/
            #SECRET_KEY: <randomly generated secret key>
        image: posthog/posthog:latest
        env_file:
            - ./.envs/.production/.posthog
        links:
            - db:db
            - redis:redis
        ports:
            - 8000:8000
            - 80:8000
volumes:
    postgres-data:
    production_traefik: {}
version: '3'
